name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_ID: ${{ secrets.CRM_DOCKER_ID }}
      DOCKER_PASSWORD: ${{ secrets.CRM_DOCKER_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make ci-docker-build
